# Generated by Django 3.2.3 on 2021-06-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductmodel',
            name='photo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
